alter table public.team_members
add column if not exists role text not null default 'member';

do $$ begin
  alter table public.team_members add constraint team_members_role_check
  check (role in ('admin', 'member'));
exception when duplicate_object then null;
end $$;

update public.team_members
set role = 'admin'
where user_id = (
  select user_id from public.team_members order by created_at asc limit 1
)
and not exists (select 1 from public.team_members where role = 'admin');

create or replace function public.assign_first_crm_admin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.team_members where role = 'admin') then
    new.role := 'admin';
  else
    new.role := 'member';
  end if;
  return new;
end;
$$;

drop trigger if exists assign_first_crm_admin_trigger on public.team_members;
create trigger assign_first_crm_admin_trigger
before insert on public.team_members
for each row execute function public.assign_first_crm_admin();

revoke insert, update on public.team_members from authenticated;
grant insert (user_id, name, email, last_seen_at) on public.team_members to authenticated;
grant update (name, email, phone, bio, status, avatar_url, last_seen_at) on public.team_members to authenticated;

alter table public.contacts
add column if not exists lead_id text references public.leads(id) on delete set null;

create unique index if not exists contacts_lead_id_unique
on public.contacts (lead_id)
where lead_id is not null;

create table if not exists public.lead_tasks (
  id bigint generated by default as identity primary key,
  lead_id text not null references public.leads(id) on delete cascade,
  title text not null,
  description text not null default '',
  due_date date,
  assigned_to uuid not null references auth.users(id),
  assigned_to_name text not null,
  assigned_to_email text not null,
  assigned_by uuid not null references auth.users(id),
  assigned_by_name text not null,
  assigned_by_email text not null,
  status text not null default 'open' check (status in ('open', 'done')),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.lead_tasks enable row level security;

create policy "YalaByte team can view lead tasks" on public.lead_tasks for select to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "YalaByte team can create lead tasks" on public.lead_tasks for insert to authenticated
with check (assigned_by = auth.uid() and lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "YalaByte team can update lead tasks" on public.lead_tasks for update to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');

grant select, insert, update on public.lead_tasks to authenticated;
grant usage, select on sequence public.lead_tasks_id_seq to authenticated;

create table if not exists public.notification_reads (
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_id bigint not null references public.lead_deletion_notifications(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (user_id, notification_id)
);

alter table public.notification_reads enable row level security;

create policy "Team members can view their notification reads"
on public.notification_reads for select to authenticated
using (user_id = auth.uid());
create policy "Team members can mark their notifications read"
on public.notification_reads for insert to authenticated
with check (user_id = auth.uid());
create policy "Team members can refresh their notification reads"
on public.notification_reads for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

grant select, insert, update on public.notification_reads to authenticated;

create or replace function public.set_team_member_role(p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_role not in ('admin', 'member') then
    raise exception 'Invalid team role.';
  end if;
  if not exists (
    select 1 from public.team_members
    where user_id = auth.uid() and role = 'admin'
  ) then
    raise exception 'Only CRM admins can change team roles.';
  end if;
  if p_user_id = auth.uid() and p_role <> 'admin' and (
    select count(*) from public.team_members where role = 'admin'
  ) = 1 then
    raise exception 'The CRM must retain at least one admin.';
  end if;
  update public.team_members set role = p_role where user_id = p_user_id;
end;
$$;

revoke all on function public.set_team_member_role(uuid, text) from public;
grant execute on function public.set_team_member_role(uuid, text) to authenticated;

create or replace function public.delete_crm_lead(p_lead_id text, p_actor_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lead_data jsonb;
  v_actor_email text;
begin
  v_actor_email := lower(coalesce(auth.jwt() ->> 'email', ''));
  if v_actor_email not like '%@yalabyte.com' then
    raise exception 'Only YalaByte team members can delete leads.';
  end if;
  if not exists (
    select 1 from public.team_members
    where user_id = auth.uid() and role = 'admin'
  ) then
    raise exception 'Only CRM admins can delete leads.';
  end if;

  select data into v_lead_data from public.leads where id = p_lead_id for update;
  if v_lead_data is null then raise exception 'Lead not found.'; end if;

  insert into public.lead_deletion_notifications (
    lead_id, lead_name, lead_data, deleted_by, deleted_by_name, deleted_by_email
  ) values (
    p_lead_id,
    coalesce(v_lead_data ->> 'name', 'Unnamed lead'),
    v_lead_data,
    auth.uid(),
    coalesce(nullif(trim(p_actor_name), ''), split_part(v_actor_email, '@', 1)),
    v_actor_email
  );
  delete from public.leads where id = p_lead_id;
end;
$$;

do $$ begin
  alter publication supabase_realtime add table public.lead_tasks;
exception when duplicate_object then null;
end $$;
