create table if not exists public.device_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text not null,
  token text not null unique,
  platform text not null check (platform in ('ios', 'android')),
  app_id text not null default 'crmbyte',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.device_tokens enable row level security;

create policy "Team members can view their device tokens"
on public.device_tokens
for select
to authenticated
using (
  user_id = auth.uid()
  and lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com'
);

create policy "Team members can register their device tokens"
on public.device_tokens
for insert
to authenticated
with check (
  user_id = auth.uid()
  and lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  and lower(user_email) like '%@yalabyte.com'
);

create policy "Team members can refresh their device tokens"
on public.device_tokens
for update
to authenticated
using (
  user_id = auth.uid()
  and lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com'
)
with check (
  user_id = auth.uid()
  and lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  and lower(user_email) like '%@yalabyte.com'
);

create policy "Team members can remove their device tokens"
on public.device_tokens
for delete
to authenticated
using (
  user_id = auth.uid()
  and lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com'
);

grant select, insert, update, delete on public.device_tokens to authenticated;
grant usage, select on sequence public.device_tokens_id_seq to authenticated;

create index if not exists device_tokens_user_id_idx on public.device_tokens (user_id);
create index if not exists device_tokens_last_seen_at_idx on public.device_tokens (last_seen_at desc);
