create table if not exists public.team_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.team_members enable row level security;

create policy "YalaByte team can view team members"
on public.team_members
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');

create policy "Team members can register themselves"
on public.team_members
for insert
to authenticated
with check (
  user_id = auth.uid()
  and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  and lower(email) like '%@yalabyte.com'
);

create policy "Team members can update themselves"
on public.team_members
for update
to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  and lower(email) like '%@yalabyte.com'
);

grant select, insert, update on public.team_members to authenticated;

create table if not exists public.lead_deletion_notifications (
  id bigint generated by default as identity primary key,
  lead_id text not null,
  lead_name text not null,
  lead_data jsonb not null,
  deleted_by uuid not null references auth.users(id),
  deleted_by_name text not null,
  deleted_by_email text not null,
  deleted_at timestamptz not null default now()
);

alter table public.lead_deletion_notifications enable row level security;

create policy "YalaByte team can view deletion notifications"
on public.lead_deletion_notifications
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');

grant select on public.lead_deletion_notifications to authenticated;

create or replace function public.delete_crm_lead(p_lead_id text, p_actor_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lead_data jsonb;
  v_actor_email text;
begin
  v_actor_email := lower(coalesce(auth.jwt() ->> 'email', ''));
  if v_actor_email not like '%@yalabyte.com' then
    raise exception 'Only YalaByte team members can delete leads.';
  end if;

  select data into v_lead_data
  from public.leads
  where id = p_lead_id
  for update;

  if v_lead_data is null then
    raise exception 'Lead not found.';
  end if;

  insert into public.lead_deletion_notifications (
    lead_id,
    lead_name,
    lead_data,
    deleted_by,
    deleted_by_name,
    deleted_by_email
  ) values (
    p_lead_id,
    coalesce(v_lead_data ->> 'name', 'Unnamed lead'),
    v_lead_data,
    auth.uid(),
    coalesce(nullif(trim(p_actor_name), ''), split_part(v_actor_email, '@', 1)),
    v_actor_email
  );

  delete from public.leads where id = p_lead_id;
end;
$$;

revoke all on function public.delete_crm_lead(text, text) from public;
grant execute on function public.delete_crm_lead(text, text) to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.team_members;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.lead_deletion_notifications;
exception
  when duplicate_object then null;
end $$;
