create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null default '',
  phone text not null default '',
  company text not null default '',
  role text not null default '',
  source text not null default 'Prospect',
  notes text not null default '',
  created_by uuid not null references auth.users(id),
  created_by_name text not null,
  created_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.contacts enable row level security;

create policy "YalaByte team can view contacts" on public.contacts for select to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "YalaByte team can create contacts" on public.contacts for insert to authenticated
with check (created_by = auth.uid() and lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "YalaByte team can update contacts" on public.contacts for update to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');

grant select, insert, update on public.contacts to authenticated;

create table if not exists public.contact_tasks (
  id bigint generated by default as identity primary key,
  contact_id uuid not null references public.contacts(id) on delete cascade,
  title text not null,
  description text not null default '',
  due_date date,
  assigned_to uuid not null references auth.users(id),
  assigned_to_name text not null,
  assigned_to_email text not null,
  assigned_by uuid not null references auth.users(id),
  assigned_by_name text not null,
  assigned_by_email text not null,
  status text not null default 'open' check (status in ('open', 'done')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.contact_tasks enable row level security;

create policy "YalaByte team can view contact tasks" on public.contact_tasks for select to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "YalaByte team can assign contact tasks" on public.contact_tasks for insert to authenticated
with check (assigned_by = auth.uid() and lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "YalaByte team can update contact tasks" on public.contact_tasks for update to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');

grant select, insert, update on public.contact_tasks to authenticated;
grant usage, select on sequence public.contact_tasks_id_seq to authenticated;

do $$ begin
  alter publication supabase_realtime add table public.contacts;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.contact_tasks;
exception when duplicate_object then null;
end $$;
