create sequence if not exists public.support_ticket_number_seq start 1;

create table if not exists public.client_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  contact_id uuid not null unique references public.contacts(id) on delete cascade,
  name text not null,
  email text not null unique,
  company text not null default '',
  status text not null default 'invited' check (status in ('invited', 'active', 'suspended')),
  invited_by uuid references auth.users(id),
  invited_at timestamptz not null default now(),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  ticket_number text not null unique default (
    'YB-' || to_char(now(), 'YY') || '-' || lpad(nextval('public.support_ticket_number_seq')::text, 4, '0')
  ),
  client_user_id uuid references auth.users(id) on delete cascade,
  contact_id uuid references public.contacts(id) on delete cascade,
  lead_id text references public.leads(id) on delete set null,
  subject text not null,
  description text not null,
  category text not null default 'Technical issue',
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  status text not null default 'new' check (status in ('new', 'in_progress', 'waiting_client', 'resolved', 'closed')),
  assigned_to uuid references auth.users(id) on delete set null,
  assigned_to_name text not null default '',
  response_due_at timestamptz,
  resolution_due_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now()
);

-- Team members may open an internal ticket directly from a lead before the
-- client receives portal access. These ALTERs also upgrade an earlier run.
alter table public.support_tickets alter column client_user_id drop not null;
alter table public.support_tickets alter column contact_id drop not null;
do $$ begin
  alter table public.support_tickets add constraint support_ticket_has_client_or_lead
  check ((client_user_id is not null and contact_id is not null) or lead_id is not null);
exception when duplicate_object then null;
end $$;

create table if not exists public.support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_email text not null,
  author_type text not null check (author_type in ('client', 'team')),
  body text not null,
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.client_profiles enable row level security;
alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;

create policy "Clients can view their profile" on public.client_profiles for select to authenticated
using (user_id = auth.uid() or lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "YalaByte team can manage client profiles" on public.client_profiles for all to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');

create policy "Clients can view their tickets" on public.support_tickets for select to authenticated
using (client_user_id = auth.uid() or lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "Clients can create their tickets" on public.support_tickets for insert to authenticated
with check (
  client_user_id = auth.uid()
  and contact_id = (select contact_id from public.client_profiles where user_id = auth.uid() and status <> 'suspended')
);
create policy "YalaByte team can create tickets" on public.support_tickets for insert to authenticated
with check (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');
create policy "YalaByte team can update tickets" on public.support_tickets for update to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com');

create policy "Ticket participants can view messages" on public.support_ticket_messages for select to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com'
  or exists (
    select 1 from public.support_tickets
    where support_tickets.id = support_ticket_messages.ticket_id
    and support_tickets.client_user_id = auth.uid()
  ) and not is_internal
);
create policy "Clients can reply to their tickets" on public.support_ticket_messages for insert to authenticated
with check (
  author_user_id = auth.uid() and author_type = 'client' and not is_internal
  and exists (
    select 1 from public.support_tickets
    where support_tickets.id = support_ticket_messages.ticket_id
    and support_tickets.client_user_id = auth.uid()
  )
);
create policy "YalaByte team can add ticket messages" on public.support_ticket_messages for insert to authenticated
with check (
  author_user_id = auth.uid() and author_type = 'team'
  and lower(coalesce(auth.jwt() ->> 'email', '')) like '%@yalabyte.com'
);

grant select, insert, update on public.client_profiles to authenticated;
grant select, insert, update on public.support_tickets to authenticated;
grant select, insert on public.support_ticket_messages to authenticated;
grant usage, select on sequence public.support_tickets_id_seq to authenticated;
grant usage, select on sequence public.support_ticket_messages_id_seq to authenticated;
grant usage, select on sequence public.support_ticket_number_seq to authenticated;

create or replace function public.touch_support_ticket()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.support_tickets
  set last_activity_at = now(), updated_at = now()
  where id = new.ticket_id;
  return new;
end;
$$;

drop trigger if exists touch_support_ticket_on_message on public.support_ticket_messages;
create trigger touch_support_ticket_on_message
after insert on public.support_ticket_messages
for each row execute function public.touch_support_ticket();

do $$ begin
  alter publication supabase_realtime add table public.support_tickets;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.support_ticket_messages;
exception when duplicate_object then null;
end $$;
